In [1]:
import sys
sys.path.append('../BPMQ')

from LinearControl import LinearModel, LinearControl, LinearControl_virtual_evaluator
import numpy as np

In [2]:
input_CSETs = ["BDS_BTS:PSC2_D5496", "BDS_BTS:PSC1_D5496"]
output_RDs = ["BDS_BTS:BPM_D5513:XPOS_RD", "BDS_BTS:BPM_D5513:YPOS_RD"]
input_dim = len(input_CSETs)
output_dim = len(output_RDs)

In [3]:
evaluator = LinearControl_virtual_evaluator(input_CSETs=input_CSETs,output_RDs=output_RDs)

In [4]:
ctr = LinearControl(evaluator=evaluator,
                    goal=np.zeros(output_dim),
                    goal_tol=np.ones(output_dim),
                    x0=np.zeros(input_dim),
                    dx=0.1*np.ones(input_dim),
                    xmin=-10*np.ones(input_dim),
                    xmax= 10*np.ones(input_dim),
                    input_RDs = input_CSETs,
                    output_RDs = output_RDs)
# ctr.initialize() 
# x,y = ctr.iterate()
ctr.run()

In [8]:
ctr.eval_dfs[0]

,BDS_BTS:BPM_D5513:XPOS_RD,BDS_BTS:BPM_D5513:YPOS_RD,BDS_BTS:PSC2_D5496,BDS_BTS:PSC1_D5496
2024-09-30 14:29:24.224960,-0.368579,-0.365635,-8.800083e-07,-1.199084e-06
2024-09-30 14:29:24.327124,-0.368580,-0.365636,4.359938e-07,-9.543400e-07
2024-09-30 14:29:24.429167,-0.368582,-0.365636,4.800436e-08,1.026237e-06
2024-09-30 14:29:24.530668,-0.368580,-0.365637,-5.375279e-07,4.597563e-07
2024-09-30 14:29:24.640277,-0.368580,-0.365637,1.147637e-06,-7.814167e-07

In [7]:
ctr.eval_dfs[-1]

,BDS_BTS:BPM_D5513:XPOS_RD,BDS_BTS:BPM_D5513:YPOS_RD,BDS_BTS:PSC2_D5496,BDS_BTS:PSC1_D5496
2024-09-30 14:29:25.971410,-0.000015,-0.000003,0.389167,1.050733
2024-09-30 14:29:26.071871,-0.000013,-0.000003,0.389165,1.050733
2024-09-30 14:29:26.172693,-0.000015,-0.000002,0.389164,1.050733
2024-09-30 14:29:26.275853,-0.000012,-0.000003,0.389165,1.050732
2024-09-30 14:29:26.377633,-0.000015,-0.000003,0.389166,1.050732

In [9]:
x,y = ctr.iterate()

In [10]:
ctr.eval_dfs[-1]

,BDS_BTS:BPM_D5513:XPOS_RD,BDS_BTS:BPM_D5513:YPOS_RD,BDS_BTS:PSC2_D5496,BDS_BTS:PSC1_D5496
2024-09-30 14:30:06.709992,-5.006278e-07,2.293222e-07,0.389179,1.050745
2024-09-30 14:30:06.810477,-2.174223e-06,4.671196e-07,0.389180,1.050743
2024-09-30 14:30:06.910877,1.264837e-07,7.731322e-07,0.389180,1.050743
2024-09-30 14:30:07.011108,-2.395616e-06,5.862346e-07,0.389179,1.050744
2024-09-30 14:30:07.111769,-1.431338e-06,-3.572861e-07,0.389181,1.050742